header:
  version : 1
  includes:
    - repo: meta-mender-kernel
      file: kas/kas.yml

repos:
  meta-mender-luks:

  meta-mender-kernel:
    url    : "https://github.com/coreycothrum/meta-mender-kernel.git"
    refspec: a8caff16f790eef0754cae895580fd799a3458cc
